// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login/CenteredElevated.tsx": () => import("../components/mockups/login/CenteredElevated.tsx"),
  "./components/mockups/login/SplitPanel.tsx": () => import("../components/mockups/login/SplitPanel.tsx")
};
