// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/company-profile/ConversationalSetup.tsx": () => import("../components/mockups/company-profile/ConversationalSetup.tsx"),
  "./components/mockups/company-profile/GuidedWizard.tsx": () => import("../components/mockups/company-profile/GuidedWizard.tsx"),
  "./components/mockups/company-profile/LiveProfileStrength.tsx": () => import("../components/mockups/company-profile/LiveProfileStrength.tsx"),
  "./components/mockups/ihale-layout/CommandPalette.tsx": () => import("../components/mockups/ihale-layout/CommandPalette.tsx"),
  "./components/mockups/ihale-layout/GridCards.tsx": () => import("../components/mockups/ihale-layout/GridCards.tsx"),
  "./components/mockups/ihale-layout/TopFilterBar.tsx": () => import("../components/mockups/ihale-layout/TopFilterBar.tsx"),
  "./components/mockups/login/CenteredElevated.tsx": () => import("../components/mockups/login/CenteredElevated.tsx"),
  "./components/mockups/login/CompactCardSplit.tsx": () => import("../components/mockups/login/CompactCardSplit.tsx"),
  "./components/mockups/login/FeatureLedTop.tsx": () => import("../components/mockups/login/FeatureLedTop.tsx"),
  "./components/mockups/login/SplitPanel.tsx": () => import("../components/mockups/login/SplitPanel.tsx"),
  "./components/mockups/login/StackedHero.tsx": () => import("../components/mockups/login/StackedHero.tsx")
};
